### ISSUE TITLE
Add method to finalize all ended ballots

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/oracles-contract#12]
Problem:
At the moment, to finalize ballots you need to create another proposal.
Solution:
Add finalize method with two behaviors
- if a ballot is provided then method finalize the ballot if the ballot is expired
- if a ballot is not provided then method finalizes all ballots

**Comment by lorien** [comment]
> if a ballot is provided then method finalize the ballot if the ballot is expired
What if ballot is not expired but quorum is reached already?

**Comment by vbaranov** [comment]
Then we go to
>...finalizes all ballots

Ballot is provided, if a) quorum is reached and b) ballot is expired.
For now, quorum is 3 and ballot duration is 48 h. Another idea is to make ballot duration flexible. Because, for example, if validator payout key is compromised, why it should wait so long to change key.

**Comment by vbaranov** [comment]
see https://github.com/oraclesorg/oracles-contract/commit/01703796617c22fcb8f92cf902984e09f77bdfef
