### ISSUE TITLE
addValidator refactoring

### ISSUE THREAD

**Issue by lorien** [oraclesorg/oracles-contract#18]
I suggest to split addValidator on two functions:
* function that handles request from voting key (add or update data)
* function that handles request from initial key (add data)

Also I suggest to move mining key data existence check into separate method. Something like:
```
function isMiningKeyDataExists(address miningKey) returns (bool) {
    bytes memory name = bytes(validator[miningKey].fullName);
    return name.length > 0;
}

**Comment by vbaranov** [comment]
See https://github.com/oraclesorg/oracles-contract/commit/1e7f00a6a81a72da0215ed3c2f863ae4823570e4
