### ISSUE TITLE
Will we increase total number of licenses?

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/oracles-contract#30]
For now, it is
>int8 internal licensesLimit = 52;

@igorbarinov

**Comment by igorbarinov** [comment]
it's a limit for initial validators + all added?

**Comment by vbaranov** [comment]
yes: from ceremony (25) + from governance = 52

**Comment by rstormsf** [comment]
lets remove the limit

**Comment by igorbarinov** [comment]
Let's set initial keys equal to 12 to match whitepaper. Validators will add more validators using governance dapp.

**Comment by vbaranov** [comment]
>Let's set initial keys equal to 12 to match whitepaper. Validators will add more validators using governance dapp.

Done

>Solution: lets remove the limit.
Rationale: we can't predict how many validators will be needed for mainnet

I agree with rationale, but doubt about solution. How about technical limit, let's say = 1000? IMO it is not a good idea to have dynamic sized array in solidity with possibility in contract to fill it with unlimited number of elements without any limits.

**Comment by vbaranov** [comment]
Tested that the technical limit is 2000. More validators in array will cause out of gas problem.
