### ISSUE TITLE
(Fix) Update README

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/oracles-contract#35]
Why:
Network launch is coming. More people will start to work on the repo soon. We need to make a clear description of the main contract repo. Contributors and auditors should understand what's happening in the network.

What:
- checks should be in tests. Create separate issues to add specific tests for each contract
- "Oracles contract definition" is not required in the README

**Comment by vbaranov** [comment]
>"Oracles contract definition" is not required in the README

moved to wiki

**Comment by vbaranov** [comment]
https://github.com/oraclesorg/oracles-contract/issues?q=is%3Aissue+is%3Aopen+label%3A%22test+required%22
