### ISSUE TITLE
Reason for hardcoded owner address

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-contract#5]
https://github.com/oraclesorg/oracles-contract/blob/master/src/owned.sol#L7

Any explanation what is this address? 
```
 owner = 0xDd0BB0e2a1594240fED0c2f2c17C1E9AB4F87126; //msg.sender
```

**Comment by igorbarinov** [comment]
This is an address of the master of ceremony of the contract. We need it for the setup. We hard coded it beause the contract bytecode will be in the spec.json file and the contract will not be deployed as a transaction. Thus, we can't refer to the owner in the contract and use hardcoded value.

The owner of the contract will be able to issue initial keys and validators will be able to remove him from the list of validators after the initial ceremony.
