### ISSUE TITLE
Convert "Common Oracles contract features checklist" into actual tests

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/oracles-contract#9]
At the moment there are no tests for contracts

**Comment by vbaranov** [comment]
Checklist is actualised.

1. https://github.com/oraclesorg/oracles-contract#validatorsstorage-and-validatorsmanager-contracts
2. https://github.com/oraclesorg/oracles-contract#keysstorage-and-keysmanager-contracts
3. https://github.com/oraclesorg/oracles-contract#ballotsstorage-and-ballotsmanager-contracts

1,2 - every item is actual test
3 - there is no tests for `BallotsManager`, `BallotsStorage` for now. Every test we need will be created in separate issue.
